name: build release

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./dialogPlus

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v3
        id: audit
        with:
          working_directory: ./dialogPlus
          production_flag: true
          json_flag: true
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,test
          dedupe_issues: true
      - name: moderate_vulns
        run: echo ::set-output name=moderate ::$(node -e "const audit={{steps.audit.outputs.npm_audit}}; console.log(audit.metadata.vulnerabilities.moderate)")
      - name: Moderate Badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: time
          LABEL: 'nap audit moderate vulns'
          STATUS: ${{ steps.moderate_vulns.outputs.moderate }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: install dependencies
      run: npm install
    - name: build pwa
      run: ./build_pwa.sh
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'iconic_adialogplus_pwa.zip'
        directory: ./dialogPlus
        path: dist
    - run: echo ::set-output name=tag_name::pwa_$(date +%d%m%y%H%M%S)
      id: set_tag_name
    - name: Upload Release
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: "./dialogPlus/iconic_adialogplus_pwa.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.set_tag_name.outputs.tag_name }}
